# Generated by Django 5.0.3 on 2024-03-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='none', upload_to='', verbose_name='image'),
        ),
    ]
